### ISSUE TITLE
how solve this?

### ISSUE THREAD

**Issue by johnfelipe** [sherwyn11/Pharma-Chain#12]
Starting migrations...
	======================
	> Network name:    'development'
	> Network id:      1641943540729
	> Block gas limit: 12000000 (0xb71b00)

	1_initial_migration.js
	======================

	   Deploying 'Migrations'
	   ----------------------

	Error:  *** Deployment Failed ***

	"Migrations" -- Returned error: sender account not recognized.

		at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
		at processTicksAndRejections (node:internal/process/task_queues:94:5)
		at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
		at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
		at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
		at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
		at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
		at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
		at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:76:1)
		at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
		at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)

**Comment by sherwyn11** [comment]
If you are testing locally, please check Ganache is up and running and also check that in the `truffle-config.js` file, the `from:` value is updated to a valid account.

**Comment by johnfelipe** [comment]
And Wich account put in that variable?

**Comment by sherwyn11** [comment]
Put an any account from the list of accounts that Ganache gives you

**Comment by johnfelipe** [comment]
Can u update repo with all needed pls

**Comment by sherwyn11** [comment]
I have updated the Readme file
